"""Conversation state constants for the wizard bot."""

MAIN_MENU, CHOOSE_METHOD, ASK_PHONE, WAITING_OTP, WAITING_PASSWORD, WAITING_QR = range(6)
TOKEN_LOGIN, ADMIN_MENU, WAITING_USER_ID = range(6, 9)
USERBOT_MENU, COMMAND_LIST, COMMAND_SETTINGS = range(9, 12)
COMMAND_CONFIG, GOOGLE_CONFIG, REPLY_GUARD_CONFIG, BROADCAST_CONFIG = range(12, 16)
